spring:
  application:
    name: back
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${DATABASE_NAME:faqdb}
    username: ${DATABASE_USERNAME:faq}
    password: ${DATABASE_PASSWORD:faq123}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:empty}